version: '3.8'

services:
  web:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/etsy
    command: >
      sh -c "flask db stamp head &&
             flask db migrate  &&
             flask db upgrade  &&
             flask run --host=0.0.0.0"
    volumes:
      - /usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - .env
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=etsy
    ports:
      - 5432:5432
